intLiterals: intLiterals.cpp
	g++ -g3 -ggdb -Wall -Wextra --std=c++20 -o intLiterals.exe intLiterals.cpp

floatsDoubles: floatsDoubles.cpp
	g++ -g3 -ggdb -Wall -Wextra --std=c++20 -o floatsDoubles.exe floatsDoubles.cpp