intLiterals: intLiterals.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o intLiterals.exe intLiterals.cpp

floatsDoubles: floatsDoubles.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o floatsDoubles.exe floatsDoubles.cpp

charTypes: charTypes.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o charTypes.exe charTypes.cpp

rangeForLoop: rangeForLoop.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o rangeForLoop.exe rangeForLoop.cpp

strArray: strArray.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o strArray.exe strArray.cpp

usrDefTypesEnum: usrDefTypesEnum.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o usrDefTypesEnum.exe usrDefTypesEnum.cpp

usrDefTypeStruct: usrDefTypeStruct.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o usrDefTypeStruct.exe usrDefTypeStruct.cpp

classMethods: classMethods.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o classMethods.exe classMethods.cpp

objInitialization: objInitialization.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o objInitialization.exe objInitialization.cpp

narrowConvrs: narrowConvrs.cpp
	g++ -g3 -ggdb -Wpedantic -Wall -Wextra -Werror --std=c++20 -o narrowConvrs.exe narrowConvrs.cpp