stepFunction: stepFunction.cpp
	g++ -g3 -ggdb -Wall -Wextra --std=c++20 -o stepFunction.exe stepFunction.cpp

absValue: absValue.cpp
	g++ -g3 -ggdb -Wall -Wextra --std=c++20 -o absValue.exe absValue.cpp